simplify SDLC and minor code cleanups
finos/legend-studio pull request #1041
Opened 2022-04-11 03:03 UTC by akphi

## Summary

- [ ] Closes #879 
- [ ] Closes #408 
- [ ] Closes #935 
- [ ] Minor code smell cleanups (detected by `Sonar`)

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/13574879/162658243-54233f2a-06e0-477d-8a2f-6376e3b43612.mov

2022-04-12 15:49 UTC, MauricioUyaguari requested changes
Can we add some tests after we go live with this please ? Thanks

2022-04-12 15:49 UTC, MauricioUyaguari commented on packages/legend-studio/src/stores/LegendStudioRouter.ts
> +  NOT_FOUND: `/notfound`,
As hopefully with this we stabalize our routes, might make sense to document this somewhere about what each url routes to.

2022-04-12 15:49 UTC, MauricioUyaguari commented on packages/legend-studio/src/components/LegendStudioApplication.tsx
> +          {/* <Route
remove this please

2022-04-12 15:49 UTC, MauricioUyaguari commented on packages/legend-studio/src/components/setup/Setup.tsx
> +                  <div className="panel__content__form__section__header__label">
Why are we using the word "import" here even when creating projects are allowed. 
Doesn't the flow make sense if
canCreateProject
  true: default to create, but allow import as another option
  false: just show import option?

2022-04-12 16:00 UTC, akphi commented on packages/legend-application/src/stores/ApplicationStore.ts
> -    if (document.queryCommandSupported('copy')) {
it's deprecated https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported, so is `execCommand`

2022-04-12 16:09 UTC, akphi commented on packages/legend-extension-dsl-diagram/src/DiagramRenderer.ts
> -          e.returnValue = false;
deprecation notice again, check `Sonar` https://sonarcloud.io/project/overview?id=legend-studio

2022-04-12 16:16 UTC, akphi commented on packages/legend-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
> +    'Service Editor basic registration functionality for projects with versions',
I'll check again later

2022-04-12 16:16 UTC, akphi commented on packages/legend-art/src/components/markdown/MarkdownTextViewer.tsx
> +      dangerouslySetInnerHTML={{
Makes sense. Should use `react-markdown` instead. Somehow `markdown-it` stucks in my mind 😆

2022-04-12 16:17 UTC, akphi commented on packages/legend-taxonomy/src/stores/LegendTaxonomyStore.ts
> +              }/view/archive/${generateGAVCoordinates(
Ukie

2022-04-14 14:21 UTC, MauricioUyaguari approved these changes

2022-04-14 16:51 UTC, merged