Show deprecated classes as strike through in query builder explorer tree
finos/legend-studio pull request #1310
Opened 2022-07-15 14:46 UTC by gayathrir11

## Summary

Closes #1303 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

![snip1](https://user-images.githubusercontent.com/87973126/179247367-e34e55c7-6305-444f-b10c-76217b3c60aa.PNG)

![snip2](https://user-images.githubusercontent.com/87973126/179247318-859e249b-1b08-41f6-b7ea-1bcf9662995c.PNG)

***Model Data***
```
###Relational
Database test::db
(
  Table DeprecatedClassTable
  (
    NAME VARCHAR(200),
    AGE INTEGER
  )
  Table NormalClassTable
  (
    NAME VARCHAR(200),
    AGE INTEGER
  )

  Join Normal_Deprecated(DeprecatedClassTable.NAME = NormalClassTable.NAME)
)

###Pure
Class <<meta::pure::profiles::doc.deprecated>> test::DeprecatedClass
{
  name: String[1];
  age: Number[1];
}

Class test::NormalClass
{
  name: String[1];
  age: Number[1];
  deprecated: test::DeprecatedClass[1];
  <<meta::pure::profiles::doc.deprecated>> deprecatedDerivedProperty() {''}: String[1];
}

###Mapping
Mapping test::mapping
(
  *test::DeprecatedClass: Relational
  {
    ~mainTable [test::db]DeprecatedClassTable
    name: [test::db]DeprecatedClassTable.NAME,
    age: [test::db]DeprecatedClassTable.AGE
  }
  *test::NormalClass: Relational
  {
    ~mainTable [test::db]NormalClassTable
    name: [test::db]NormalClassTable.NAME,
    age: [test::db]NormalClassTable.AGE,
    deprecated[test_DeprecatedClass]: [test::db]@Normal_Deprecated
  }
)
```

2022-07-19 04:12 UTC, MauricioUyaguari commented on packages/legend-query/src/components/QueryBuilderSetupPanel.tsx
> +    val.stereotypes.find((st) => st.ownerReference.value === deprecatedProfile)
Although this technically works, its not fully correct. We should assert that the stereotype is the Deprecated one below. 

Another stereotype could be added to the list of stereotypes and would be caught in this condition. 
```
Profile meta::pure::profiles::doc
{
  stereotypes: [deprecated];
  tags: [doc, todo];
}
```

2022-07-19 04:13 UTC, MauricioUyaguari requested changes
small comment

2022-07-20 13:30 UTC, MauricioUyaguari commented on packages/legend-query/src/components/QueryBuilderSetupPanel.tsx
> +  if (val.stereotypes.find((st) => st.value.value === DEPRECATED_STEREOTYPE)) {
Still think there is an issue here. 
You are only checking the stereotype value. 
Could be 
`meta::other::profile::OTHERPROFILE.deprecated`

Correct isEqual should be `graph.getProfile({PureProfile}).getStereotype(Deprecated) === st.value`.
one could argue we could have a `pureProfile` getter on PureModel for the first part

2022-07-20 13:31 UTC, MauricioUyaguari requested changes
small comment

2022-07-20 14:40 UTC, akphi requested changes

2022-07-20 14:43 UTC, akphi commented on packages/legend-graph/src/MetaModelConst.ts
> +export const DEPRECATED_STEREOTYPE = 'deprecated';
Let's move it below `CORE_PURE_PATH` and rename this to `PURE_DEPRECATED_STEREOTYPE`

2022-07-20 15:12 UTC, gayathrir11 commented on packages/legend-query/src/stores/QueryBuilderExplorerState.ts
> +  if (parentNode.isDeprecated === true) {
yeah deprecation propagates to all the child nodes

2022-07-21 14:57 UTC, akphi commented
> ![snip1](https://user-images.githubusercontent.com/87973126/180153001-44dcb660-26e4-4f44-a800-550a896ecba9.PNG)

Let's not `strike-through` the `(...)`

2022-07-21 15:01 UTC, MauricioUyaguari requested changes

2022-07-22 12:57 UTC, akphi commented on packages/legend-graph/src/helpers/DomainHelper.ts
> +  element: AnnotatedElement | Class,
nice!

2022-07-22 12:59 UTC, akphi commented on packages/legend-query/src/stores/QueryBuilderExplorerState.ts
> +  graph: PureModel,
Let's remove since we nolonger need this.

2022-07-22 13:01 UTC, akphi requested changes
Looking good, just left some comments about code organization, otherwise, we are ready to roll. Thanks!

2022-07-22 13:01 UTC, akphi commented on packages/legend-query/src/stores/QueryBuilderExplorerState.ts
> +export const checkForDeprecatedPropertyNode = (
We can move this utility to the component and remove the `export`

2022-07-22 14:48 UTC, akphi commented on packages/legend-query/src/components/QueryBuilderExplorerPanel.tsx
> +const checkForDeprecatedPropertyNode = (
```suggestion
const checkForDeprecatedNode = (
```

2022-07-22 14:48 UTC, akphi approved these changes

2022-07-22 15:10 UTC, MauricioUyaguari approved these changes

2022-07-22 15:10 UTC, merged