Fix creating new milestoned query from dataspace
finos/legend-studio pull request #1327
Opened 2022-07-22 10:20 UTC by gayathrir11

## Summary

closes #1315 

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-07-27 20:05 UTC, YannanGao-gs commented
@gayathrir11  Looks good to me :)

2022-07-28 13:20 UTC, MauricioUyaguari requested changes

2022-07-28 13:20 UTC, MauricioUyaguari commented on packages/legend-application-query/src/stores/QueryEditorStore.ts
> -    // initialize query builder state after setting up
why are we removing these lines ?

2022-07-28 14:36 UTC, MauricioUyaguari requested changes

2022-07-28 14:36 UTC, MauricioUyaguari commented on packages/legend-application-query/src/stores/QueryEditorStore.ts
>        this.queryBuilderState.querySetupState._class = getNullableFirstElement(
what happens if the class selected here is milestoned. Should we also use the `changeClass` method here

2022-07-28 15:13 UTC, MauricioUyaguari approved these changes

2022-07-28 15:13 UTC, merged