Block certain actions when query is not valid
finos/legend-studio pull request #1359
Opened 2022-08-01 09:02 UTC by gayathrir11

## Summary

closes #1345 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/87973126/182113269-1bb54dd9-d3d0-492a-b1e8-87bb311fa218.mp4

2022-08-01 19:17 UTC, YannanGao-gs commented
@gayathrir11  What's the current behavior if users want to set the filter value to an empty string?

2022-08-01 22:59 UTC, MauricioUyaguari commented on packages/legend-application-query/src/components/QueryBuilderFilterPanel.tsx
> +    const isEmptyNode = (): boolean =>
Empty string values are valid inputs.

2022-08-01 23:02 UTC, MauricioUyaguari requested changes

2022-08-01 23:02 UTC, MauricioUyaguari commented on packages/legend-application-query/src/stores/QueryBuilderProjectionState.ts
> +    const hasDuplicatedProjectionColumns = this.columns.some(
lets make this a bit more readable. 
We can do something like 
```
if(this.queryBuilderState.fetchStructureState.isProjectionMode)
{
   // duplicate cols check
  // no cols check 
}
return true;
````

2022-08-03 15:56 UTC, YannanGao-gs commented on packages/legend-application-query/src/stores/QueryBuilderProjectionState.ts
> +          this.columns.filter((c) => c.columnName === column.columnName)
the time complexity of duplication check is O(n^2) 
too high

2022-08-03 18:13 UTC, MauricioUyaguari commented on packages/legend-application-query/src/stores/QueryBuilderFilterState.ts
> +      nodes: observable,
why do we need this?

2022-08-03 18:13 UTC, MauricioUyaguari requested changes
why do we need this?

2022-08-05 15:25 UTC, MauricioUyaguari approved these changes

2022-08-05 15:26 UTC, merged