Support creation of self-referenced associations in form mode
finos/legend-studio pull request #1425
Opened 2022-08-17 18:05 UTC by YannanGao-gs

## Summary
Fixes https://github.com/finos/legend-studio/issues/1398

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/73408381/185210988-bff93bf1-dd52-4995-a232-5c760c398366.mov

2022-08-19 15:50 UTC, MauricioUyaguari requested changes
looks good to me, lets fix the code checks

2022-08-20 03:39 UTC, akphi commented
@YannanGao-gs did we check how this might interact with https://github.com/finos/legend-studio/pull/1180 ?

2022-08-22 10:19 UTC, gayathrir11 commented
This is how it looks after #1180 
![Capture](https://user-images.githubusercontent.com/87973126/185898619-53faafc8-7edf-48f1-93e3-e1fb576a01c5.PNG)

2022-08-23 18:41 UTC, MauricioUyaguari approved these changes

2022-08-23 18:41 UTC, merged