Thang
finos/legend-studio pull request #1602
Opened 2022-10-30 03:28 UTC by akphi

## Summary

- [x] Update `V1_ValueSpecification` per the change in https://github.com/finos/legend-engine/pull/1063:
  - [x] Reorganized
  - [x] Update to use static multiplicities
  - [x] Document about `V1_ClassInstance` and `V1_CoreClassInstance`
  - [x] Updated `V1_ValueSpecification` and `V1_ValueSpecificationVisitor` to support the latest list of value specification
  - [x] Take care of (de)serialization of different `V1_ClassInstance` and introduce extension mechanism for it: e.g. `serialize(V1_mappingModelSchema(this.plugins), element)`
- [x] Remove all explicit support for `V1_HackedUnit` and `V1_HackedClass`, these now should be removed all together and converted to `V1_GenericTypeInstance`.
- [x] Handle CString with value as empty list: follow the change in https://github.dev/finos/legend-engine/pull/1076
- [x] Update `value spec` builder/transform/path-resolver logic, and anything else that implements `V1_ValueSpecificationVisitor`roundtrip test for value specification
- [x] Hard-code all multiplicity for all primitive value specification
  - [x] Remove `multiplicity` field from serialization schema for all of `V1_PrimitiveValueSpecification`
  - [x] Globally use static `Multiplicity` and `V1_Multiplicity`: we should not see
  - [x] Set the type to `Nil` - // for arguments of types we don't support, we will fill them with `[]` - Check location: `return new CollectionInstanceValue(graph.getTypicalMultiplicity(TYPICAL_MULTIPLICITY_TYPE.ZERO));`, we now create an utility method to represent nullish value
- [x] Adjust value specification metamodels:
  - [x] Eradicate the following value specification metamodels and their visitors
        // visit_AlloySerializationConfigInstanceValue(valueSpecification: AlloySerializationConfigInstanceValue): T;
        // visit_RuntimeInstanceValue(valueSpecification: RuntimeInstanceValue): T;
        // visit_PairInstanceValue(valueSpecification: PairInstanceValue): T;
        // visit_MappingInstanceValue(valueSpecification: MappingInstanceValue): T;
        // visit_PureListInstanceValue(valueSpecification: PureListInstanceValue): T;
        // visit_PropertyGraphFetchTreeInstanceValue(PropertyGraphFetchTreeInstanceValue: PureListInstanceValue): T;
  - [x] Rename `RootGraphFetchTreeInstanceValue` to `GraphFetchTreeInstanceValue`
  - [x] Document about why we have different kinds of `InstanceValue`: move them all into one file and document there, we don't have a powerful matcher like in `Pure`, see https://github.com/finos/legend-engine/blob/94cd0aff3b314e568e830773f7200c8245baa09b/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure#L254
- [x] Remove `TYPICAL_MULTIPLICITY_TYPE` and `PureModel.getTypicalMultiplicity()`

## How did you test this change?

- [x] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-11-01 18:49 UTC, MauricioUyaguari requested changes
great!

2022-11-01 18:51 UTC, akphi commented on packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_PersistenceCloud-basic.pure
> -###Pure
It's duplicated of the other test and it's faulty, i.e. `PersistentContext` is not compiling right now

2022-11-01 18:51 UTC, akphi commented on packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_Persistence-basic.pure
> -PersistenceContext org::legend::ZooPersistenceContext
see above

2022-11-01 18:51 UTC, akphi commented on packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/function/V1_ConcreteFunctionDefinition.ts
> +  /**
yes

2022-11-01 18:52 UTC, akphi commented on packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_MappingSerializationHelper.ts
> +            includedMapping:
wut?

2022-11-02 01:21 UTC, MauricioUyaguari approved these changes

2022-11-02 01:21 UTC, merged