Update sequent lambda names once the filter root lambda parameter name is changed
finos/legend-studio pull request #1623
Opened 2022-11-03 13:49 UTC by YannanGao-gs

## Summary

Fixes https://github.com/finos/legend-studio/issues/1622

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/73408381/199738159-b8a3df1a-4de2-48ee-8909-6fcfaa20180c.mov

2022-11-03 15:14 UTC, MauricioUyaguari requested changes

2022-11-03 15:14 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
> +  (currentExpression as VariableExpression).name = lambdaParameterName;
why is this needed?

2022-11-03 20:14 UTC, YannanGao-gs commented on packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
> +  (currentExpression as VariableExpression).name = lambdaParameterName;
updated code as suggested

2022-11-05 03:22 UTC, MauricioUyaguari approved these changes

2022-11-05 03:22 UTC, merged