query builder fixes
finos/legend-studio pull request #1669
Opened 2022-11-09 02:07 UTC by xannem

## Summary

## How did you test this change?

- [x] Text editor to light mode
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/41248956/200718222-8d9ff2e4-ff4a-49cb-8a20-eefaac3b4532.png">

- [x]  Misc light mode edits
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/41248956/202810509-a5324b57-f434-476c-8854-8cf810f01f8c.png">
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/41248956/202810600-33790307-a52e-4c94-a849-5e5c02cd14c1.png">

- [x] String inputs for filter value now has a button that will allow user more space to input text. If the user's input has multiple lines, the elements will be separated by new lines. If the user input has one line, the inputs will be separated by commas.
![Kapture 2022-11-24 at 00 29 58](https://user-images.githubusercontent.com/41248956/203701973-b0ab6ad1-d1ac-43d9-8442-bb93bdd1fe5e.gif)

# Testing

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-11-09 18:00 UTC, akphi requested changes

2022-11-09 18:00 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +  if (parseResult.data[0]?.length === 1) {
we should abstract this out to an utility function and test with some inputs, e.g. `1,3,4,6\n7,8,8,9\n,10`

2022-11-14 06:03 UTC, akphi requested changes

2022-11-14 06:03 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +    const [openedPopUp, setOpenedPopUp] = useState(false);
let's rename this:

```suggestion
    const [showAdvancedEditorPopover, setShowAdvancedEditorPopover] = useState(false);
```

2022-11-14 06:03 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +          {openedPopUp && (
I think we should use a popover here instead. Modal is a little too strong.

2022-11-14 06:03 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +              title="Open..."
Please change the title tooltip text to something more descriptive

2022-11-14 06:03 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +              className="lambda-editor__action"
why are we using this class here?

2022-11-14 06:03 UTC, akphi commented on packages/legend-art/style/base/_modal.scss
> +.editor-modal--small {
If we are to use the popover as suggested below, we don't need this change.

2022-11-14 06:05 UTC, akphi commented
Also, @xannem let's include the UI change you made to the OLAP panel (light/dark mode). Also, can you fix a minor issue where in query builder, when we open the result set modifier (under TDS panel), the take limit input has no visible outline in light theme?

2022-11-18 21:20 UTC, xannem commented on packages/legend-shared/src/CommonUtils.ts
> + * NOTE: this splits a string value into an array of strings by using a
Yep that's what I believe we both discussed should be the case for now 🙇

2022-11-18 21:59 UTC, xannem commented on packages/legend-shared/package.json
> +    "@types/papaparse": "5.3.5",
It is used in legend-shared but still needed in legend-query-builder for `stringifyValue` for `ValueSpecification` things 🙇

2022-11-20 02:32 UTC, akphi requested changes

2022-11-20 02:32 UTC, akphi commented on packages/legend-shared/package.json
> +    "@types/papaparse": "5.3.5",
then let's move that method over to `@finos/legend-shared` as well

2022-11-20 02:32 UTC, akphi commented on packages/legend-shared/src/CommonUtils.ts
> +export const parseCSVString = (value: string): string[] | undefined => {
This should be in `FormatterUtils.ts`, not here.

2022-11-20 02:32 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +          {showAdvancedEditorPopover && (
Looking at the video preview, I think when we're showing the popover, we should not show anything in the `input` field, it looks odd, you can even consider moving the popover to completely eclipse the original input box, by manipulating `menuProps.anchorOrigin and menuProps.transformOrigin`. Also, add a small box at the bottom of the popover to say - hit `Enter` to apply change, `Esc` and `click-out` action should not save the result <-- this is also the behavior in `vscode`, look at vscode when you try to create a new file in the explorer tree sidebar, that's kind of the visual guide and interaction I hope we have.

2022-11-24 05:45 UTC, xannem commented on packages/legend-shared/package.json
> +    "@types/papaparse": "5.3.5",
The `stringifyValue` method uses CVSParser to unparse but checks if the value is instance of `PrimitiveInstanceValue` or `EnumValueInstanceValue` and takes in `ValueSpecification[]`, so I did originally try moving it but then seeing as those are all types that didn't belong in `legend-shared` and shouldn't be imported I thought maybe the method was ok to be left here?

2023-01-11 03:20 UTC, MauricioUyaguari commented
@xannem lets bring this PR back to life. So many great changes here :)

2023-01-13 15:28 UTC, MauricioUyaguari approved these changes

2023-01-13 15:29 UTC, merged