fix:Fix a bug where re-editing `filter`and 'post filter' input is not possible
finos/legend-studio pull request #1705
Opened 2022-11-17 16:54 UTC by YannanGao-gs

## Summary

Fixes https://github.com/finos/legend-studio/issues/1594
## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

https://user-images.githubusercontent.com/73408381/202508375-f20d1d4e-2a76-4904-8f3e-a656175c075c.mov

2022-11-17 17:32 UTC, akphi requested changes

2022-11-17 17:32 UTC, akphi commented on packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
> +            inputValue={selectedValue.value}
I think we can just put `value` here instead.
Also, please help me fix the CSS problem with the line height of this input box 🙏

2022-11-17 17:32 UTC, akphi commented on .changeset/shy-pears-beg.md
> +Fix a bug where re-editing `filter` and `post filter` input is not possible ([#1594](https://github.com/finos/legend-studio/issues/1594)).
```suggestion
Fix a bug with the cursor when editing `filter` and `post filter` text input value ([#1594](https://github.com/finos/legend-studio/issues/1594)).
```

2022-11-17 20:23 UTC, akphi approved these changes

2022-11-17 20:55 UTC, merged

2022-11-19 08:40 UTC, MauricioUyaguari commented
@YannanGao-gs  as discussed, this breaks when selecting an option from the type ahead options, so let's address that. Thanks