#179 Fix/association property edit
finos/legend-studio pull request #180
Opened 2021-04-30 11:47 UTC by kshradhan

| Q                       | A                                |
| ----------------------- | -------------------------------- |
| Fixed issues?           | Fixes: #179  |
| Tests added + passed?   | Yes                              |
| Changeset added?        | No |
| Documentation PR link   |                                  |
| Any dependency changes? | No                               |

Added a check to delete otherProperty from associations only when it is already populated and not when it is first created

2021-04-30 14:44 UTC, akphi requested changes

2021-04-30 14:44 UTC, akphi commented on packages/legend-studio/src/models/metamodels/pure/model/packageableElements/domain/Association.ts
> +    otherPropertyAssociatedClass.propertiesFromAssociations.length &&
can we use a normal `if` here?

2021-04-30 14:44 UTC, akphi commented
@kshradhan you would need to sign the CLA, also, make sure to add changeset to your change.

2021-04-30 14:45 UTC, akphi commented on packages/legend-studio/src/models/metamodels/pure/model/packageableElements/domain/Association.ts
> +    otherPropertyAssociatedClass.propertiesFromAssociations.length &&
Also my concern here why is the `propertiesFromAssociations` of the other class is empty? Did we mess up building the graph at some point?

2021-04-30 14:48 UTC, MauricioUyaguari reviewed
Please add an association editor test here. Follow the UMLEditortest. Make it simple.

2021-05-03 13:59 UTC, kshradhan commented
> Please add an association editor test here. Follow the UMLEditortest. Make it simple.

Done

2021-05-03 14:06 UTC, akphi commented on .changeset/healthy-kings-give.md
> +Add test for Association Viewer
You don't need a message when you add test like this. You can delete this changeset as the other one should already suffice

2021-05-03 14:08 UTC, akphi commented on packages/legend-studio/src/components/editor/edit-panel/uml-editor/__tests__/UMLEditor.test.tsx
>  // Unable to find an element with the text: temporal. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your mat
:) can you help us delete this out-of-context comment? Thanks!

2021-05-03 14:12 UTC, akphi commented on packages/legend-studio/src/components/editor/edit-panel/uml-editor/__tests__/UMLEditor.test.tsx
>  // Unable to find an element with the text: temporal. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your mat
Ah, nvm, I took care of it

2021-05-03 14:14 UTC, akphi commented on packages/legend-studio/src/models/metamodels/pure/model/packageableElements/domain/Association.ts
> +    if (otherPropertyAssociatedClass.propertiesFromAssociations.length) {
Like I mentioned before, I get this error, but what you're doing here is handling the code smell, you haven't addressed the actual problem, which is the fact that we messed up graph building somewhere.

2021-05-06 10:40 UTC, kshradhan commented
Closing this due to misconfigured histories because of wrong email address

2021-05-06 10:40 UTC, closed without merging