Make filter and post-filter behavior clearer in query builder
finos/legend-studio pull request #2079
Opened 2023-04-06 16:29 UTC by xannem

## Summary

fixes #1995

![Kapture 2023-04-06 at 12 26 06](https://user-images.githubusercontent.com/41248956/230440151-e04c2109-75ad-488f-a5c6-0fc270eb6ea1.gif)

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings) (ux changes)
- [ ] No testing (please provide an explanation)

2023-04-10 11:47 UTC, gayathrir11 submitted a review, later dismissed

2023-04-25 18:33 UTC, akphi requested changes

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/src/panel/BlankPanelPlaceholder.tsx
> +  draggableActive?: boolean | undefined;
--> `showDropableSuggestion`

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/src/panel/PanelDropZone.tsx
> +  draggableActive?: boolean | undefined;
```suggestion
  showDropableSuggestion?: boolean | undefined;
```

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/src/panel/PanelDropZone.tsx
> +        'draggable--active': draggableActive,
```suggestion
        'dnd__dropzone--dropable': draggableActive,
```

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
> +            {' '}
let's remove these

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
> +    // svp0
can we do a quick scan again to clean these up? Thanks!

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/src/panel/BlankPanelPlaceholder.tsx
> +  draggableActive?: boolean | undefined;
can we document this flag to differentiate it from the `isDropZoneActive` flag?

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
> +export const IS_DRAGGABLE_FILTER_DND_TYPES_FETCHSUPPORTED = [
```suggestion
export const IS_DRAGGABLE_FILTER_DND_TYPES_FETCH_SUPPORTED = [
```

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/src/panel/PanelDropZone.tsx
> +  draggableActive?: boolean | undefined;
We should think about the interaction between this and the overlay, I think the border here should be on a layer that is beneath the overlay and above the content, also, it should be absolutely position to not jank the layout

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/src/panel/BlankPanelPlaceholder.tsx
> +          'draggable--active': draggableActive,
We should design this in a way that it doesn't cause the layout to jank

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/style/_query-builder-filter.scss
> +    &--potential__dropzone {
--> `--dropable`

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/style/_query-builder-filter.scss
> +    &--potential__dropzone {
again, for these, we should think of a way to make them absolutely position to not jank the layout

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/style/_query-builder-post-filter.scss
> +    &--potential__dropzone {
--> `--dropable`

again, for these, we should think of a way to make them absolutely position to not jank the layout

2023-04-25 18:33 UTC, akphi commented on packages/legend-art/style/base/_common.scss
> +.dnd__entry-potential__dropzone__indicator {
some of these styles are fine to be here, some of them better off be in `query buidler`, for example, specializations like `--full`, `--tall`, etc.

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
> +    const { isPotentiallyDragging } = useDragLayer((monitor) => ({
--> `showDropableSuggestion`

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
> +            {' '}
let's clean up these `{' '}` next time please

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
> +    const { isPotentiallyDragging } = useDragLayer((monitor) => ({
let's find a way so we don't have to duplicate the code like this, shall we?

2023-04-25 18:33 UTC, akphi commented on packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
> +        {isPotentiallyDragging ? (
let's find a way so we don't have to duplicate the code like this, shall we?

2023-06-07 14:41 UTC, akphi requested changes
Looks good to me, though you have some CI failures there. Also, it's a TODO that we think of the problem with DnD I told you a while back, can you file a Github issue for that? Thanks!

2023-06-07 15:56 UTC, akphi approved these changes

2023-06-07 16:16 UTC, merged