Add extesnion for export other feature
finos/legend-studio pull request #2321
Opened 2023-06-09 13:43 UTC by gayathrir11

## Summary

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2023-06-12 13:11 UTC, gayathrir11 commented
/easycla

2023-06-12 14:28 UTC, xannem commented on packages/legend-query-builder/style/_query-builder.scss
> +    height: 30vh;
Perhaps add increased sizing for height so codeeditor has more space for content?

2023-06-14 23:55 UTC, akphi requested changes

2023-06-14 23:55 UTC, akphi commented on .changeset/ninety-horses-fry.md
> +Add extension mechanism for export other feature.
```suggestion
Add extension mechanism for export query to other formats.
```

2023-06-14 23:55 UTC, akphi commented on .changeset/ninety-horses-fry.md
> +'@finos/legend-query-builder': patch
```suggestion
'@finos/legend-query-builder': minor
```

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/stores/QueryBuilder_LegendApplicationPlugin_Extension.ts
> +  getExportOtherOptions?(): ExportOtherOption[];
```suggestion
  getExtraQueryUsageConfigurations?(): QueryUsageConfiguration[];
```

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/stores/QueryBuilder_LegendApplicationPlugin_Extension.ts
> +  title: string;
@xannem not sure I get your point here

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/stores/QueryBuilder_LegendApplicationPlugin_Extension.ts
> +  content: string;
I foresee we would need to have more than just the text here, this should be a renderer for the tab content, think about something similar to `DataSpace` quick start

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/stores/QueryBuilder_LegendApplicationPlugin_Extension.ts
> +   * Get the list of export other options
```suggestion
   * Get the list of query usage configurations
```

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/stores/QueryBuilder_LegendApplicationPlugin_Extension.ts
> +export type ExportOtherOption = {
```suggestion
export type QueryExportUsageConfiguration = {
```

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/components/QueryBuilderExportOtherViewer.tsx
> +export const QueryBuilderExportOtherViewer = observer(
Let's rename all `ExportOther` -> `Usage`, e.g. here `QueryUsageViewer`

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
> +  isExportOtherModalOpened = false;
let's rename these and its related to `isQueryUsageViewerOpen`

2023-06-14 23:55 UTC, akphi commented on packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
> +                    Other
Suffix `...` as this prompts user for further actions

```suggestion
                    View Query Usage...
```

2023-06-20 05:45 UTC, akphi requested changes

2023-06-20 05:45 UTC, akphi commented on packages/legend-query-builder/src/components/QueryUsageViewer.tsx
> +                  Export options are not available
Shouldn't we update the language here as well?

2023-06-20 05:45 UTC, akphi commented on packages/legend-query-builder/src/components/QueryUsageViewer.tsx
> +          <ModalHeader title="Query Usage Options" />
```suggestion
          <ModalHeader title="Query Usage" />
```

2023-06-20 14:20 UTC, akphi approved these changes

2023-06-20 14:20 UTC, merged