Limit DND rearrange option in query
finos/legend-studio pull request #2330
Opened 2023-06-13 18:10 UTC by xannem

## Summary
Fixes https://github.com/finos/legend-studio/issues/2311 

Isolates the rearranging action to only when user is also pressing the `alt` button 
![Kapture 2023-06-13 at 14 10 00](https://github.com/finos/legend-studio/assets/41248956/a29ac8b5-b4ac-46ef-ac01-9fdff778bb5f)

 

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2023-06-17 13:38 UTC, gayathrir11 approved these changes

2023-06-25 05:18 UTC, akphi requested changes
@xannem TODO: please add the fix for re-arrange and I'll review one more round

2023-06-27 16:24 UTC, akphi approved these changes
TODO: for TDS projection column re-arrange: there are known limitations to the current drop location indicator that happens when drag-and-dropping the first/last item. I think we get the right spirit but we should go back and smoothen out those edge cases at some point

2023-06-27 16:33 UTC, merged

2023-06-27 20:59 UTC, xannem commented
> TODO: for TDS projection column re-arrange: there are known limitations to the current drop location indicator that happens when drag-and-dropping the first/last item. I think we get the right spirit but we should go back and smoothen out those edge cases at some point

Issue added: https://github.com/finos/legend-studio/issues/2380