Added support to choose from only valid combinations of database type…
finos/legend-studio pull request #2356
Opened 2023-06-21 19:30 UTC by yash0024

…, source and authentication when creating a relational connection

## Summary
- Updated the UI so that only valid combinations of Datasource and Authentication strategies are shown given the database type.

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [x] No testing (please provide an explanation)

(tried to add a video/screenshot but the files don't process)

2023-06-21 21:05 UTC, xannem commented on .yarnrc.yml
> +npmRegistryServer: http://npmscopes.site.gs.com
You can remove these parts the `.yarnrc.yml` shouldn't need to be part of your commit and can be ignored 👍

2023-06-21 21:06 UTC, xannem commented on packages/legend-application-studio/src/components/editor/editor-group/connection-editor/RelationalDatabaseConnectionEditor.tsx
> -      Object.values(CORE_DATASOURCE_SPEC_TYPE) as string[]
as discussed offline, remove unused imports of `CORE_DATASOURCE_SPEC_TYPE` and `CORE_AUTHENTICATION_STRATEGY_TYPE`

2023-06-21 21:09 UTC, xannem commented on packages/legend-application-studio/src/stores/graph-modifier/STO_Relational_GraphModifierHelper.ts
> +    con;
Are you doing something with this method?

2023-06-21 21:10 UTC, xannem requested changes
+comments

2023-06-28 13:49 UTC, xannem approved these changes

2023-06-28 17:11 UTC, xannem commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.5.0.cjs
```suggestion
yarnPath: .yarn/releases/yarn-3.5.0.cjs

```

2023-06-28 18:51 UTC, MauricioUyaguari commented
major concern is for auth and datasource that are not part of core legend-studio. lets say we add an auth calleed 'myAuth' and It is valid for H2.

2023-06-28 20:14 UTC, MauricioUyaguari commented
As discussed with @xannem 
 there are more database types that a user can select with extensions, 
so you will need to edit the extension mechnaism to take in the database type and only return datasource speficiations/auth strategies that match the database type.

2023-06-28 20:16 UTC, MauricioUyaguari commented on packages/legend-application-studio/src/stores/editor/editor-state/element-editor-state/connection/ConnectionEditorState.ts
> +  get selectedValidDatasources(): Array<CORE_DATASOURCE_SPEC_TYPE> {
CORE_DATASOURCE_SPEC_TYPE[]

2023-06-28 20:16 UTC, MauricioUyaguari commented on packages/legend-application-studio/src/stores/editor/editor-state/element-editor-state/connection/ConnectionEditorState.ts
> +  get selectedValidAuthenticationStrategies(): Array<CORE_AUTHENTICATION_STRATEGY_TYPE> {
CORE_AUTHENTICATION_STRATEGY_TYPE[]

2023-08-23 15:41 UTC, closed without merging