Added form support for Execution Plan
finos/legend-studio pull request #2392
Opened 2023-06-30 14:26 UTC by Paarth002

## Summary

Added form support for Execution Plan. Added Global Implementation Support for Execution Plan.

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2023-07-06 06:55 UTC, gayathrir11 commented
![general](https://github.com/finos/legend-studio/assets/87973126/41138ac5-d620-4872-a340-102d12d175f6)

![global](https://github.com/finos/legend-studio/assets/87973126/0eb65cbb-b9ac-4000-a54f-e92872146c75)

2023-07-06 15:26 UTC, YannanGao-gs commented on packages/legend-graph/src/graph-manager/protocol/pure/v1/transformation/pureGraph/from/executionPlan/V1_ExecutionPlanTransformer.ts
> +function transformJavaClass(metamodel: JavaClass): V1_JavaClass {
I think it might be better to call it `v1_transformJavaClass`

2023-07-10 09:26 UTC, gs-ssh16 commented
/easycla

2023-07-11 13:07 UTC, MauricioUyaguari requested changes

2023-07-11 13:10 UTC, MauricioUyaguari submitted a review, later dismissed

2023-07-11 13:11 UTC, MauricioUyaguari requested changes

2023-07-11 13:11 UTC, MauricioUyaguari commented on .changeset/three-wolves-roll.md
> +Added form for global implementation in executionplan
````suggestion
Added form for global implementation in execution plan
````

2023-07-11 14:13 UTC, MauricioUyaguari approved these changes

2023-07-11 14:14 UTC, merged