Fix error message being shown for duplicated elements
finos/legend-studio pull request #2454
Opened 2023-07-26 13:40 UTC by gayathrir11

## Summary

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

![error](https://github.com/finos/legend-studio/assets/87973126/b63b5a00-39eb-44e2-9e5d-bac4f4063d3d)

2023-07-27 15:48 UTC, MauricioUyaguari reviewed
small comment. Thanks!

2023-08-01 14:35 UTC, akphi requested changes

2023-08-01 14:35 UTC, akphi commented on packages/legend-graph/src/graph/MetaModelConst.ts
> +  CURRENT_GRAPH = 'current graph',
for current graph, we probably don't need to mention anything

2023-08-01 14:35 UTC, akphi commented on packages/legend-graph/src/graph/PureModel.ts
> +  getElementOrigin(path: string, includePakcage?: boolean): string | undefined {
Also, I think these are a little expensive, should we call methods like `isSystemElement`, `isGeneratedElement`, etc.?

2023-08-01 14:35 UTC, akphi commented on packages/legend-graph/src/graph-manager/__tests__/buildGraph/GraphBuildFailure.test.ts
> +    `Current graph element 'ui::test1::Animal' already exists in current graph`,
```suggestion
    `Element 'ui::test1::Animal' already exists`,
```

2023-08-01 14:35 UTC, akphi commented on packages/legend-graph/src/graph-manager/__tests__/buildGraph/Dependency.test.ts
> +      `Current graph element 'model::ClassB' already exists in dependency group-1:artifact-1`,
```suggestion
      `Element 'model::ClassB' already exists in dependency group-1:artifact-1`,
```

2023-08-01 14:35 UTC, akphi commented on packages/legend-graph/src/graph/MetaModelConst.ts
> +export enum ELEMENT_ORIGIN {
can we maybe use `ROOT_PACKAGE_NAME` instead to not have to create yet another categorization that is semantically equivalent?

2023-08-02 07:20 UTC, gayathrir11 commented on packages/legend-graph/src/graph/PureModel.ts
> +  getElementOrigin(path: string, includePakcage?: boolean): string | undefined {
I don't think we have that file anymore.

2023-08-02 10:59 UTC, akphi commented on packages/legend-graph/src/graph/PureModel.ts
> +  getElementOrigin(path: string, includePakcage?: boolean): string | undefined {
so let's do `DomainHelper` I guess

2023-08-02 11:08 UTC, akphi requested changes

2023-08-02 11:08 UTC, akphi commented on packages/legend-graph/src/graph/PureModel.ts
> +  getElementOrigin(
this and the one in dependency manager's method signature make little sense, let's just do `getElementOrigin(element: PackageableElement): string | undefined`

2023-08-02 11:08 UTC, akphi commented on packages/legend-graph/src/graph/PureModel.ts
> +      _origin = ROOT_PACKAGE_NAME.SYSTEM.slice(0, -5);
this looks really bizzare, why don't we just hard-code text here, after all, this method is basically a `pretty print` of element origin.

2023-08-07 14:14 UTC, merged