Add Generate Models button to enable autogeneration of classes, associations, and mapping feature for relational databases
finos/legend-studio pull request #2455
Opened 2023-07-26 13:41 UTC by jake-kim1

##Summary

This PR adds a "Generate Models" button when right-clicking on a relational database, which calls the API for autogeneration of classes, and associations, and mapping.

2023-07-31 16:25 UTC, MauricioUyaguari requested changes
can we add a video of the workflow here. Not sure I agree with the approach of just generating the models directly without first showing the users the models that will be added to the project. this is the approach we do for generate database and we should follow a similar approach.

2023-07-31 16:25 UTC, MauricioUyaguari commented on .changeset/sixty-carpets-cheat.md
> +Add Generate Models button to enable autogeneration of classes, associations, and mapping feature for relational databases
lets separate this to two changeste files

The above message can stay for `@finos/legend-application-studio` but should be a `minor` change. 
For the `@finos/legend-graph` we can keep empty.

2023-07-31 19:34 UTC, YannanGao-gs commented on packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
> +          const graph: PureModel = editorStore.graphManagerState.graph;
coudl we remove ': PureModel'?

2023-07-31 19:44 UTC, MauricioUyaguari requested changes

2023-07-31 19:44 UTC, MauricioUyaguari commented on .changeset/sixty-carpets-cheat.md
> +Add Generate Models button to enable autogeneration of classes, associations, and mapping feature for relational databases
````suggestion
---
'@finos/legend-application-studio': minor
'@finos/legend-graph': minor
---
Support generating models from relational database. 
````

2023-07-31 19:44 UTC, MauricioUyaguari commented on packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
> +          const graph: PureModel = editorStore.graphManagerState.graph;
````suggestion
          const graph = editorStore.graphManagerState.graph;
````

2023-07-31 19:44 UTC, MauricioUyaguari commented on packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
> +          const databasePath: string = guaranteeNonEmptyString(
````suggestion
          const databasePath = guaranteeNonEmptyString(
````

2023-07-31 20:00 UTC, MauricioUyaguari commented on packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
> +  type PureModel,
````suggestion
 Database,
````

2023-07-31 21:10 UTC, MauricioUyaguari approved these changes

2023-07-31 21:11 UTC, merged

2023-08-10 01:23 UTC, jake-kim1 commented
https://github.com/finos/legend-studio/assets/60619826/4fdc50b1-c4b1-460d-a219-c511835024ef