Add custom execution editor for InlineServicePureExecutionState
finos/legend-studio pull request #2538
Opened 2023-08-22 05:23 UTC by hardikmaheshwari

## Summary
InlineServicePureExecution does not have any context so we should remove that window to have bigger space for users to view the query in a glance

## How did you test this change?

- [ ] Test(s) added
- [X] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2023-08-22 05:56 UTC, hardikmaheshwari commented
@MauricioUyaguari @akphi can you please review when you get a chance

2023-08-22 18:52 UTC, MauricioUyaguari requested changes
Could we add a screenshot of this new look for inline services. thanks

2023-08-22 18:52 UTC, MauricioUyaguari commented on .changeset/young-suits-sort.md
> +Add custom execution edior for InlineServicePureExecutionState
````suggestion
Remove execution context editor for inline service queries
````

2023-08-23 13:25 UTC, MauricioUyaguari approved these changes

2023-08-23 13:25 UTC, merged