Support patch release in studio
finos/legend-studio pull request #2555
Opened 2023-08-30 13:49 UTC by gayathrir11

## Summary

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2023-09-07 15:26 UTC, MauricioUyaguari commented
Video Comments: 
when creating a patch with workspace, seems like we are missing feedback after hitting create. Could we do loading indicator + some kind of message, `Creating Patch...` `Creating workspace...` etc.

2023-09-08 09:30 UTC, gayathrir11 commented
> Video Comments: when creating a patch with workspace, seems like we are missing feedback after hitting create. Could we do loading indicator + some kind of message, `Creating Patch...` `Creating workspace...` etc.
> 
> When creating workspace from the welcome screen. Could we add a descriptor for workspace source. We can say something about using only when working toward a patch release.

Done

2023-09-11 19:00 UTC, akphi requested changes

2023-09-12 05:49 UTC, gayathrir11 commented on packages/legend-server-sdlc/src/SDLCServerClient.ts
> +    patchReleaseVersionId: string | undefined,
Sure. Will modify it

2023-09-13 14:16 UTC, akphi approved these changes

2023-09-13 21:50 UTC, merged