Fixed the issue where fails to target the correct row after sorting columns in query builder result panel
finos/legend-studio pull request #2622
Opened 2023-09-21 15:56 UTC by YannanGao-gs

## Summary

Fixed the issue where fails to target the correct row after sorting columns in query builder result panel

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2023-09-21 19:59 UTC, MauricioUyaguari commented
can you include the grammar for the video on this PR so we can all test more quickly?

2023-09-21 20:09 UTC, YannanGao-gs commented
```
###Service
Service model::SimpleService
{
  pattern: '/00f53db5-3b6e-48ab-bb6c-8b2edb41a55e';
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: var: Integer[1]|model::Person.all()->filter(
      x|$x.age ==
        $var
    )->project(
      [
        x|$x.age
      ],
      ['Age']
    );
    mapping: model::RelationalMapping;
    runtime: model::Runtime;
  }
}


###Relational
Database model::MyDatabase
(
  Table FirmTable
  (
    id INTEGER PRIMARY KEY,
    Legal_name VARCHAR(200),
    Inc VARCHAR(200)
  )
  Table PersonTable
  (
    id INTEGER PRIMARY KEY,
    firm_id INTEGER,
    firstName VARCHAR(200),
    lastName VARCHAR(200),
    age INTEGER
  )

  Join FirmPerson(PersonTable.firm_id = FirmTable.id)
)


###Pure
Profile model::MyExtension
{
  stereotypes: [important];
  tags: [doc];
}

Enum model::IncType
{
  Corp,
  LLC
}

Class <<model::MyExtension.important>> {model::MyExtension.doc = 'This is a model of a firm'} model::Firm extends model::LegalEntity
[
  validName: $this.legalName->startsWith('_')
]
{
  employees: model::Person[1..*];
  incType: model::IncType[1];
  isApple: Boolean[1];
  employeeSize() {$this.employees->count()}: Number[1];
}

Class model::Person
{
  firstName: String[1];
  lastName: String[1];
  age: Integer[1];
  fullName() {$this.firstName + ' ' + $this.lastName}: String[1];
}

Class model::LegalEntity
{
  legalName: String[1];
}


###Mapping
Mapping model::RelationalMapping
(
  *model::Firm: Relational
  {
    ~primaryKey
    (
      [model::MyDatabase]FirmTable.id
    )
    ~mainTable [model::MyDatabase]FirmTable
    legalName: concat([model::MyDatabase]FirmTable.Legal_name, '_LTD'),
    employees[model_Person]: [model::MyDatabase]@FirmPerson,
    isApple: case(equal([model::MyDatabase]FirmTable.Legal_name, 'Apple'), 'true', 'false'),
    incType: EnumerationMapping model_IncType: [model::MyDatabase]FirmTable.Inc
  }
  *model::Person: Relational
  {
    ~primaryKey
    (
      [model::MyDatabase]PersonTable.id
    )
    ~mainTable [model::MyDatabase]PersonTable
    firstName: [model::MyDatabase]PersonTable.firstName,
    lastName: [model::MyDatabase]PersonTable.lastName,
    age: [model::MyDatabase]PersonTable.age
  }

  model::IncType: EnumerationMapping
  {
    Corp: ['Corp', 'CORP'],
    LLC: ['LLC']
  }
)


###Connection
RelationalDatabaseConnection model::MyConnection
{
  store: model::MyDatabase;
  type: H2;
  specification: LocalH2
  {
    testDataSetupSqls: [
      'Drop table if exists FirmTable;\nDrop table if exists PersonTable;\nCreate Table FirmTable(id INT, Legal_Name VARCHAR(200), Inc VARCHAR(200));\nCreate Table PersonTable(id INT, firm_id INT, lastName VARCHAR(200), firstName VARCHAR(200), age INT);\nInsert into FirmTable (id, Legal_Name, Inc) values (1, \'Finos\', \'CORP\');\nInsert into FirmTable (id, Legal_Name, Inc) values (2, \'Apple\', \'Corp\');\nInsert into FirmTable (id, Legal_Name, Inc) values (3, \'GS\', \'Corp\');\nInsert into FirmTable (id, Legal_Name, Inc) values (4, \'Google\', \'Corp\');\nInsert into FirmTable (id, Legal_Name, Inc) values (5, \'Alphabet\', \'LLC\');\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (1, 3, \'X1\', \'Mauricio\', 10);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (2, 3, \'X2\', \'An\', 20);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (3, 3, \'X3\', \'Anne\', 30);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (4, 3, \'X4\', \'Gayathri\', 40);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (5, 3, \'X5\', \'Yannan\', 50);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (6, 3, \'X6\', \'Dave\', 60);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (7, 3, \'X7\', \'Mo\', 70);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (8, 3, \'X9\', \'Teddy\', 80);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (9, 2, \'X8\', \'Teddy\', 90);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (10, 2, \'X8\', \'Teddy\', 100);\nInsert into PersonTable (id, firm_id, lastName, firstName, age) values (10, 2, \'X9\', \'John\', 10000);\n\n\n'
      ];
  };
  auth: DefaultH2;
}


###Runtime
Runtime model::Runtime
{
  mappings:
  [
    model::RelationalMapping
  ];
  connections:
  [
    model::MyDatabase:
    [
      my_connection: model::MyConnection
    ]
  ];
}

```

2023-09-25 21:25 UTC, YannanGao-gs commented
file for future reference. 
can't launch context menu
```
      const appleCell = guaranteeNonNullable(
        Array.from(
          queryBuilderResultPanel.getElementsByClassName(
            'query-builder__result__tds-grid',
          ),
        ).filter((cell) => cell.innerHTML.includes('Apple'))[0],
      );
      fireEvent.click(appleCell);
      fireEvent.contextMenu(appleCell);
      const contextMenu = await waitFor(() => screen.getByRole('menu'));

      fireEvent.click(getByText(contextMenu, 'Filter By'));
      const queryBuilderPostFilter = await waitFor(() =>
        renderResult.getByTestId(
          QUERY_BUILDER_TEST_ID.QUERY_BUILDER_POST_FILTER,
        ),
      );
      await waitFor(() => findByText(queryBuilderPostFilter, 'Apple'));
```

2023-09-28 11:21 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/__tests__/QueryBuilderResultPanel.test.ts
> +      // Test filter out/by after sorting column
lets please enhance the execution result loaded here to be a bit more complex. With links, null values, number as strings etc. 

Also what erorr do you get with context menu?

2023-10-04 22:07 UTC, MauricioUyaguari requested changes

2023-10-04 22:07 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
> +      resultState.rowData.filter((data) => data.rowNumber === rowIndex)[0]![
I think instead of filter we should do find
`resultState.rowData.filter`
Also is this part intended `[0]![colName]` ? what is that suppose to mean

2023-10-04 22:07 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
> +    const findRowFromRowIndex = (rowIndex: number): string => {
are we even using rowIndex in this function?

2023-10-04 22:27 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
> +  getRowData(): PlainObject<unknown>[] {
Record<string, RecordValue>[]

2023-10-04 22:28 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
> +        return value.substring(0, value.lastIndexOf(','));
we need to rewrite this to better explain

2023-10-06 02:39 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
> +      const valueArr: unknown[] = [];
no `unknown` types please

2023-10-06 14:46 UTC, MauricioUyaguari approved these changes

2023-10-06 14:47 UTC, merged