Fix DnD of nested group operation with exists filter
finos/legend-studio pull request #2662
Opened 2023-10-03 10:38 UTC by gayathrir11

## Summary

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

***Creating nested group with source simple property and target exists property***

https://github.com/finos/legend-studio/assets/87973126/a9b5ebd6-cff8-4aef-a80c-bf3c74bb392e

***Creating nested group with target simple property and source exists property***

https://github.com/finos/legend-studio/assets/87973126/8088c4fa-545d-45dd-be52-15881c53f36e

***Creating nested group with source and target exists property***

https://github.com/finos/legend-studio/assets/87973126/0e8b0231-df16-484e-9bb9-48b682bedaba

***Creating group condition from menu options***

https://github.com/finos/legend-studio/assets/87973126/159c6a68-7f73-42e6-955e-29eb96e6a385

2023-10-04 21:36 UTC, MauricioUyaguari requested changes

2023-10-05 06:16 UTC, gayathrir11 commented on packages/legend-query-builder/src/components/__tests__/QueryBuilderFilterPanel.test.tsx
> +    const filterTree = await waitFor(() =>
I don't think I have defined filter Tree above

2023-10-05 07:21 UTC, gayathrir11 commented on packages/legend-query-builder/src/components/__tests__/QueryBuilderFilterPanel.test.tsx
> +    await waitFor(() =>
You mean searching for a particular node from the list of nodes and then assert on expected content for that node?

2023-10-05 18:40 UTC, MauricioUyaguari approved these changes

2023-10-05 18:40 UTC, merged