Read meta::pure::functions::date::firstDayOfYear as a Date function
finos/legend-studio pull request #2886
Opened 2024-01-22 21:37 UTC by YannanGao-gs

## Summary

Read meta::pure::functions::date::firstDayOfYear as a Date function

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

1.

https://github.com/finos/legend-studio/assets/73408381/14ac1234-c468-4f3c-8ad4-72a55b80893b

2. fix the css

https://github.com/finos/legend-studio/assets/73408381/23bf0a33-fc22-41c0-acee-897db01062fc

2024-01-24 23:54 UTC, MauricioUyaguari requested changes

2024-01-24 23:54 UTC, MauricioUyaguari commented on .changeset/curly-cars-burn.md
> +Read meta::pure::functions::date::firstDayOfYear as a Date function
lets update this to include the month function we including

2024-01-24 23:55 UTC, MauricioUyaguari commented on .changeset/curly-cars-burn.md
> +Read meta::pure::functions::date::firstDayOfYear as a Date function
````suggestion
Read `meta::pure::functions::date::firstDayOfYear` and `meta::pure::functions::date::firstDayOfMonth` as a Date functions
````

2024-01-24 23:55 UTC, MauricioUyaguari commented
@YannanGao-gs  looks good, lets rebase. thanks!

2024-01-25 14:13 UTC, YannanGao-gs commented
> @YannanGao-gs looks good, lets rebase. thanks!

rebased thanks!

2024-01-25 15:46 UTC, MauricioUyaguari approved these changes

2024-01-25 15:47 UTC, merged