feat: enable text-mode in read-only mode
finos/legend-studio pull request #312
Opened 2021-07-01 19:09 UTC by umarphaarook

| Q                       | A                                |
| ----------------------- | -------------------------------- |
| Fixed issues?           | Fixes #297  |
| Tests added + passed?   | No                              |
| Changeset added?        | Yes                              |
| Documentation PR link   |                                  |
| Any dependency changes? | No                               |

2021-07-02 17:04 UTC, akphi requested changes

2021-07-02 17:04 UTC, akphi commented on .changeset/tiny-crews-tell.md
> +Allow users to toggle hackermode/text-mode while in viewer mode.
```suggestion
Allow users to use text-mode while viewing project in read-only mode.
```

2021-07-02 17:04 UTC, akphi commented on packages/legend-studio/src/components/editor/edit-panel/GrammarTextEditor.tsx
> +        readOnly: editorStore.isInViewerMode,
Let's not set this here, but instead in the `if (editor)` block, because this `useEffect` will only be called once when we initialize the editor

2021-07-02 17:04 UTC, akphi commented on packages/legend-studio/src/stores/EditorStore.tsx
> +          (this.sdlcState.currentRevision || this.isInViewerMode),
I don't think this is the right place to do this, are you just trying to unblock hotkey here? If so, what you could do is to tackle `createGlobalHotKeyAction`

2021-07-06 15:50 UTC, akphi submitted a review, later dismissed
LGTM

2021-07-06 15:51 UTC, akphi commented
@umarphaarook did you get approved for you CLA yet?

2021-07-06 19:30 UTC, umarphaarook commented
> @umarphaarook did you get approved for CLA yet?

Nope, they are still on it.

2021-07-07 15:37 UTC, akphi commented
@cla-bot[bot] check

2021-07-13 14:42 UTC, akphi commented
@cla-bot[bot] check

2021-07-13 16:11 UTC, akphi approved these changes

2021-07-13 16:11 UTC, merged