Add milestoning setup in Query Option
finos/legend-studio pull request #3148
Opened 2024-05-14 17:52 UTC by YannanGao-gs

## Summary

Add milestoning setup in Query Option

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2024-05-16 13:32 UTC, MauricioUyaguari requested changes

2024-05-16 13:32 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/__tests__/QueryBuilderMilestoning.test.tsx
> +    await waitFor(() => getAllByText(resultModifierPanel, 'businessDate'));
lets add to this test please. i.e changing the milestone date value, setting it allVersions, using a constant etc.

2024-05-16 13:32 UTC, MauricioUyaguari commented on packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSPanel.tsx
> +              {tdsState.queryBuilderState.milestoningState.startDate &&
Is this condition correct, doesn't alllVersions dont require dates as input?

2024-05-16 17:01 UTC, YannanGao-gs commented
Add logic to handle `cancel` and `apply`

2024-05-20 06:54 UTC, gayathrir11 approved these changes

2024-05-20 14:26 UTC, MauricioUyaguari approved these changes

2024-05-20 14:26 UTC, merged