Support use function pointer in curated dataspace template query
finos/legend-studio pull request #3344
Opened 2024-07-11 19:01 UTC by YannanGao-gs

## Summary

Support use function pointer in curated dataspace template query

Depends on https://github.com/finos/legend-engine/pull/2955

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2024-07-21 22:03 UTC, MauricioUyaguari requested changes

2024-07-21 22:03 UTC, MauricioUyaguari commented on packages/legend-extension-dsl-data-space/src/graph-manager/protocol/pure/DSL_DataSpace_PureProtocolProcessorPlugin.ts
> +                                executableProtocol.query as V1_PackageableElementPointer
what is this for ?

2024-08-25 21:01 UTC, MauricioUyaguari commented
can this be closed ?

2024-08-26 13:07 UTC, YannanGao-gs commented
closed by https://github.com/finos/legend-studio/pull/3447

2024-08-26 13:07 UTC, closed without merging