add workflow side bar for viewer mode
finos/legend-studio pull request #778
Opened 2022-01-12 15:41 UTC by MauricioUyaguari

## Summary

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-01-19 10:52 UTC, akphi commented on .changeset/gold-chicken-return.md
> +"@finos/legend-studio": patch
--> `minor`

2022-01-19 17:15 UTC, akphi requested changes
Minor comments. Thanks for doing it this way. I think you start to click with my `abstract class everything` vibe 👨‍🎤

2022-01-19 17:15 UTC, akphi commented on packages/legend-studio/src/stores/sidebar-state/WorkflowsState.ts
> +export class UnsupportedWorkflowsState extends WorkflowsState {
This is not a bad idea, but why don't we just do `workflowState?: WorkflowState`. This seems quite overkill to me...

2022-01-21 16:51 UTC, akphi requested changes

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/components/editor/side-bar/WorkflowManager.tsx
> +              {workflowManagerState.label}
Shou;dn't we call this `Workflow Manager`?

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/components/editor/side-bar/WorkflowManager.tsx
> +export const UnsupportedWorkflowManager = observer(() => (
Let's remove this

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/components/viewer/Viewer.tsx
> +      case ACTIVITY_MODE.WORKFLOWS:
Let's not even render this when there's no workflow state

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/stores/ViewerStore.ts
> +  initWorkflowsState(): void {
--> `initWorkflowManagerState`

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/stores/sidebar-state/WorkflowManagerState.ts
> +  override get version(): string | undefined {
Let's call `_version` `version` and this as `versionId`?

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/stores/sidebar-state/WorkflowManagerState.ts
> +    return `PROJECT WORKFLOWS ${this.version ? `VERSION ${this.version}` : ''}`;
Maybe I mistaken, but I thought this is for the header title of the sidebar panel, then we should always keep it as `Workflow Manager`, yeah? If so we can remove this `label()`

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/stores/EditorConfig.ts
> +  WORKFLOWS = 'WORKFLOWS',
--> `WORKFLOW_MANAGER`

2022-01-21 16:51 UTC, akphi commented on packages/legend-studio/src/stores/ViewerStore.ts
> +  initWorkflowsState(): void {
--> `initWorkflowManagerState`

2022-01-24 15:18 UTC, akphi requested changes

2022-01-24 15:18 UTC, akphi commented on packages/legend-studio/src/components/editor/side-bar/WorkflowManager.tsx
> +      workflowsState: WorkflowManagerState;
--> `workflowManagerState`
Let's rename all `workflowsState` to `workflowMangerState`

2022-01-24 15:18 UTC, akphi commented on packages/legend-studio/src/stores/sidebar-state/WorkflowManagerState.ts
> +    workflowsState: WorkflowManagerState,
--> `workflowManagerState`

2022-01-24 15:18 UTC, akphi commented on packages/legend-studio/src/stores/sidebar-state/WorkflowManagerState.ts
> +  *fetchAllWorkJobs(
-> `fetchAllWorkflowJobs`

2022-01-25 14:09 UTC, MauricioUyaguari commented on packages/legend-studio/src/stores/sidebar-state/WorkflowManagerState.ts
> +    makeObservable(this, {
Nope its not.

2022-01-25 18:23 UTC, akphi commented on packages/legend-studio/src/stores/sidebar-state/WorkflowManagerState.ts
> +    makeObservable(this, {
@MauricioUyaguari  ![image](https://user-images.githubusercontent.com/13574879/151036268-4fa60835-0262-4e1b-b406-421f3cdf7465.png)

2022-01-25 18:24 UTC, akphi approved these changes

2022-01-25 18:25 UTC, merged