Introduce extension mechanism consistently and exhaustively for class…
finos/legend-studio pull request #893
Opened 2022-02-28 11:59 UTC by gayathrir11

… mapping

## Summary

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-03-03 13:01 UTC, akphi commented
@gayathrir11 for stability, I think let's merge this post `4.0.0` release.

2022-06-17 04:38 UTC, akphi requested changes
Thank you for doing this! There are a few places where I think we introduced the extension mechanism at the wrong place, I have pointed out how we could rectify these. Other cases are mostly renaming things.

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
>  const getMappingElementByTypeAndId = (
This bit of logic looks really silly now.

I think the reason why we ever introduced the concept of `MAPPING_ELEMENT_SOURCE_ID_LABEL` was to properly identify the class mapping, but I don't think that's needed. We can basically remove all `MAPPING_ELEMENT_SOURCE_ID_LABEL.X` and replace them by `MAPPING_ELEMENT_TYPE.CLASS` when constructing the `lambaId`.

Also, I think

```ts
return (
        getAllClassMappings(mapping).find(
          (classMapping) => classMapping.id.value === id,
        ) ??
        getMappingEmbeddedSetImplementations(mapping)
          .filter(filterByType(EmbeddedFlatDataPropertyMapping))
          .find((me) => me.id.value === id)
      );
```

could be used for all `case MAPPING_ELEMENT_TYPE.CLASS:` So we technically don't need the plugin method here.

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +export type BackDropElementGetter = (
InstanceSetImplementationBlockingErrorChecker

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +   * Get the list of extra mapping elements by using type and Id.
Also, for these comments, let's remove the word `extra`. Thanks!

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  getExtraBackDropElements?(): BackDropElementGetter[];
--> `getExtraInstanceSetImplementationBlockingErrorCheckers`. The documentation for this is something like `Get the list of checkers for errors in the specified instance set implementation that could potentially block the user interaction until fixed (e.g. parser error in some property mapping transform lambda editor)`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +   * Get the list of extra property mapping editors.
--> `Get the list of property mapping editor renderers`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  getExtraPropertyMappingsEditors?(): PropertyMappingsEditor[];
--> `getExtraPropertyMappingEditorRenderers`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  getExtraSourceTypesAndNames?(): SourceTypeAndNameGetter[];
--> `getExtraMappingSourceTypeInfoGetters`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +   * Get the list of extra source types and names.
--> Get the list of mapping source type info getters

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
> +          } else if (newMappingElement instanceof SetImplementation) {
Looks like we're doing it at the wrong place here, we should move this to

```ts
// here?
throw new IllegalStateError(
                  'Expected to have current mapping editor state to be of consistent type with current mapping element',
                );
```

So we should have something like `InstanceSetImplementationEditorCompilationErrorRevealer`. Not the nicest name, I have to agree :(

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +export type CompilationErrorRevealer = (
--> `InstanceSetImplementationEditorCompilationErrorRevealer`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  setImplementation: SetImplementation,
--> `instanceSetImplementation: InstanceSetImplementation`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  getExtraCompilationErrorRevealers?(): CompilationErrorRevealer[];
-->

```ts
/**
 * Get the list of compilation error revealers for the specified instance set implementation editor
 * 
 * This is marked as temporary as we might not need this mechanism anymore if we implement
 * the new error reveal mechanism
 * See https://github.com/finos/legend-studio/issues/1168
 */
TEMPORARY__getExtraInstanceSetImplementationEditorCompilationErrorRevealers?(): InstanceSetImplementationEditorCompilationErrorRevealer[]; 


```

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
> +        if (setImplementation instanceof InstanceSetImplementation) {
not only we need to do this, but we also need to modify the `if` blocks above this, so the top level conditionals only check for the tpytype of the set implementation, for example

```ts
if (setImplementation instanceof PureInstanceSetImplementation) {
  if (newSource instanceof Class || newSource === undefined) {
    pureInstanceSetImpl_setSrcClass(setImplementation, newSource);
  }
} else if (
...
```

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +export type ClassMappingSourceDriver = (
--> `InstanceSetImplementationSourceUpdater`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  newSource: MappingElementSource | undefined,
It's interesting to think how we could modularize this `MappingElementSource`.

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +) => boolean;
--> `void`?

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +  getExtraClassMappingSourceDrivers?(): ClassMappingSourceDriver[];
--> `getExtraInstanceSetImplementationSourceUpdaters`

2022-06-17 04:38 UTC, akphi commented on packages/legend-studio/src/stores/DSLMapping_LegendStudioPlugin_Extension.ts
> +   * Get the list of extra class mapping source drivers.
--> `Get the list of instance set implementation source updaters`

2022-06-17 10:32 UTC, gayathrir11 commented on packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts
>  };
@akphi do you there would be an issue if I throw an error when i don't find any store instead of returning `undefined`?

2022-06-23 16:15 UTC, akphi approved these changes
Thank you so much @gayathrir11 Let's keep rolling with flat-data, relational, etc.

2022-06-23 16:15 UTC, akphi commented on packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
> +                const extraCompilationErrorRevealers =
Thinking about it, I don't think we need this, we can simplify the check up there to `this.currentTabState instanceof InstanceSetImplementationState`

2022-06-23 16:15 UTC, akphi commented on packages/legend-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationEditor.tsx
> +    let hasParseError = false;
--> `extraInstanceSetImplementationBlockingErrorChecker`

2022-06-23 16:15 UTC, akphi commented on packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
> +          for (const instanceSetImplementationSourceUpdaters of extraInstanceSetImplementationSourceUpdaters) {
--> `instanceSetImplementationSourceUpdater`

2022-06-23 16:16 UTC, merged