Display databases and classes from dependency projects in the source option dropdown
finos/legend-studio pull request #897
Opened 2022-02-28 20:52 UTC by YannanGao-gs

## Summary

Fixed https://github.com/finos/legend-studio/issues/890

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-02-28 22:18 UTC, akphi requested changes

2022-02-28 22:18 UTC, akphi commented on .changeset/gold-shirts-switch.md
> +---
Let's be mindful of changeset granuality. This change should be split across 2 files. The message you wrote is relevant only for Studio

2022-02-28 22:18 UTC, akphi commented on .changeset/gold-shirts-switch.md
> +Display databases and classes from dependency projects in the source options dropdown.
Should also add `in mapping editor`

2022-02-28 23:05 UTC, MauricioUyaguari commented on .changeset/shy-rockets-melt.md
> +Update the dependencyManager to include databases.
@akphi  I think a change this small probably doesn't need a changeset log. Thoughts?

2022-03-01 01:21 UTC, akphi commented on .changeset/gold-shirts-switch.md
> +Display databases and classes from dependency projects in the source options dropdown in the mapping editor.
```suggestion
Display `database tables/views` and `classes` from dependency projects in the source selector dropdown in the mapping editor.
```

2022-03-01 01:22 UTC, akphi approved these changes

2022-03-01 02:03 UTC, merged