Add support for post requests and refactor service store mapping models
finos/legend-studio pull request #900
Opened 2022-03-02 14:20 UTC by hardikmaheshwari

## Summary
These changes will let users fetch data from post api's by generating request bodies at runtime.
These changes also refactor the current ServiceStore mapping models to better align with the concepts.

## How did you test this change?

- [ X] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-03-03 05:44 UTC, hardikmaheshwari commented
@MauricioUyaguari @akphi Can you please review these changes?
Roundtrip tests will be fixed once attached engine PR is merged

2022-03-03 16:24 UTC, akphi commented on packages/legend-extension-external-store-service/src/models/metamodels/pure/model/packageableElements/store/serviceStore/mapping/ServiceMapping.ts
> +  pathOffset: object | undefined; // @MARKER GENERATED MODEL DISCREPANCY --- Studio does not process lambda
-> `?:`

2022-03-03 16:24 UTC, akphi commented on packages/legend-extension-external-store-service/src/models/metamodels/pure/model/packageableElements/store/serviceStore/mapping/ServiceMapping.ts
> +  requestBuildInfo: ServiceRequestBuildInfo | undefined;
-> `?:`

2022-03-03 16:30 UTC, akphi requested changes

2022-03-03 16:30 UTC, akphi commented on packages/legend-extension-external-store-service/src/models/metamodels/pure/model/packageableElements/store/serviceStore/mapping/ServiceMapping.ts
> +  pathOffset: object | undefined; // @MARKER GENERATED MODEL DISCREPANCY --- Studio does not process lambda
-> `?:`

2022-03-03 16:30 UTC, akphi commented on packages/legend-extension-external-store-service/src/models/metamodels/pure/model/packageableElements/store/serviceStore/mapping/ServiceMapping.ts
> +  requestBuildInfo: ServiceRequestBuildInfo | undefined;
-> `?:`

2022-03-03 16:30 UTC, akphi commented on packages/legend-extension-external-store-service/src/models/metamodels/pure/model/packageableElements/store/serviceStore/mapping/ServiceRequestBuildInfo.ts
> +  requestBodyBuildInfo: ServiceRequestBodyBuildInfo | undefined;
Let's use `?:` as its more correct, the value sent by engine is optional or `undefined`

2022-03-03 16:30 UTC, akphi commented on packages/legend-extension-external-store-service/src/models/protocols/pure/v1/model/packageableElements/store/serviceStore/mapping/V1_ServiceParameterMapping.ts
> + */
We probably should mention in the changeset that we `deprecate` these.

2022-03-11 05:55 UTC, hardikmaheshwari commented
> @hardikmaheshwari yup, let's switch it to `non draft` next time 😛

@akphi I marked it as draft as I don't want this to be merged before engine PR's 
Thanks for reviewing

2022-03-24 02:38 UTC, akphi approved these changes
I'll remove the deprecated models actually. `studio` will quietly ignore ignored properties while parsing anyway.

2022-03-24 02:38 UTC, merged