Add support for DateTime valuespecification editor
finos/legend-studio pull request #909
Opened 2022-03-03 12:02 UTC by gayathrir11

## Summary

Closes #842 

## How did you test this change?

- [ ] Test(s) added
- [ ] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)
![Screenshot 2022-03-03 172911](https://user-images.githubusercontent.com/87973126/156561099-d3239926-2d4e-4f94-b465-2db3c4e0105a.png)

2022-03-03 12:19 UTC, akphi requested changes

2022-03-03 12:19 UTC, akphi commented on packages/legend-query/src/components/QueryBuilderValueSpecificationEditor.tsx
> +          type="datetime-local"
@MauricioUyaguari what should it be here? `local` or `UTC`?

2022-03-03 12:19 UTC, akphi commented on .changeset/slimy-spiders-hope.md
> +Add support for `DateTime` valueSpecification editor
```suggestion
Add support for `DateTime` value specification editor ([#842](https://github.com/finos/legend-studio/issues/842))
```

2022-03-03 12:20 UTC, akphi commented
@gayathrir11 Let's add a quick video for this. Thanks!

2022-03-03 12:28 UTC, gayathrir11 commented
> @gayathrir11 Let's add a quick video for

> @gayathrir11 Let's add a quick video for this. Thanks!

![Screenshot 2022-03-03 172911](https://user-images.githubusercontent.com/87973126/156564723-a4504ede-aa85-44ed-aff7-ee388c3edeb9.png)
 It looks like this. I don't like it.  Thinking of a better design

2022-03-03 12:37 UTC, akphi commented
> > @gayathrir11 Let's add a quick video for this. Thanks!
> 
> ![Screenshot 2022-03-03 172911](https://user-images.githubusercontent.com/87973126/156564723-a4504ede-aa85-44ed-aff7-ee388c3edeb9.png)
> 
> It looks like this. I don't like it. Looking for a better design

It's fine 😛 that's the default from browser. We don't need to ask for more now.

2022-03-03 16:17 UTC, akphi commented on packages/legend-query/src/components/QueryBuilderValueSpecificationEditor.tsx
> +          type="datetime-local"
I think we should do `UTC`

2022-03-03 16:18 UTC, akphi commented
@gayathrir11 let's add video to the PR description about setting this and going in/out of text mode (kinda a roundtrip)

2022-03-03 16:29 UTC, gayathrir11 commented
> @gayathrir11 let's add video to the PR description about setting this and going in/out of text mode (kinda a roundtrip)

Cool i will add video but the recording wouldn't show the editor actually and it's in the execute panel so i don't think there will be any changes to the query

2022-03-03 16:33 UTC, akphi commented
> > @gayathrir11 let's add video to the PR description about setting this and going in/out of text mode (kinda a roundtrip)
> 
> Cool i will add video but the recording wouldn't show the editor actually and it's in the execute panel so i don't think there will be any changes to the query so nothing will be actually visisble in text mode

Why though? We could show a video when you use this in filter?

2022-03-03 19:14 UTC, akphi commented on packages/legend-query/src/components/QueryBuilderValueSpecificationEditor.tsx
> +          type="datetime-local"
Could we try this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#setting_timezones
so we set the timezone to UTC?

2022-03-05 12:53 UTC, akphi approved these changes
I'll test out this change myself, if it does not suffice, I can roll back.

2022-03-05 12:54 UTC, merged

2022-03-07 18:02 UTC, akphi commented on packages/legend-query/src/components/QueryBuilderValueSpecificationEditor.tsx
> +          type="datetime-local"
Turns out `datetime-local` already assume `UTC` 😆 so we're good I guess

2022-03-07 18:03 UTC, akphi commented
Turns out the `datetime-local` actually worked with `UTC` by default - see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#setting_timezones

We're good folks!