adopt new grammar-JSON transformation API endpoints
finos/legend-studio pull request #960
Opened 2022-03-14 22:35 UTC by akphi

## Summary

Closes #877

**Note**: we should wait for https://github.com/finos/legend-engine/pull/595 to be merged first

## How did you test this change?

- [ ] Test(s) added
- [x] Manual testing (please provide screenshots/recordings)
- [ ] No testing (please provide an explanation)

2022-03-24 16:51 UTC, akphi commented
@cla-bot[bot] check

2022-05-23 18:49 UTC, MauricioUyaguari requested changes

2022-05-23 18:49 UTC, MauricioUyaguari commented on packages/legend-studio/src/stores/editor-state/element-editor-state/FunctionEditorState.ts
> +        this.functionElement.body = lambda.body as object[];
did we validate a lambda of empty string works with this ?

2022-05-23 19:52 UTC, MauricioUyaguari approved these changes

2022-05-23 19:59 UTC, merged